	
// Code generated by EvalFunction. Just for eyeball check
package thomas
import (
	"encoding/json"
	"fmt"
	"log"
	"os"
)

var (
	Trace     = log.New(os.Stdout, "TRACE: ", log.Ldate|log.Ltime|log.Lshortfile)
	// StructMap = make(map[string]func([]byte) ([]string, error))
)
	 type Template1 struct {
 Person struct {
  Name struct {
   First    string `json:"first"`
   Last     string `json:"last"`
   FullName string `json:"fullName"`
  } `json:"name"`
  Github struct {
   Handle    string `json:"handle"`
   Followers int    `json:"followers"`
  } `json:"github"`
  Avatars []struct {
   Ff     int64  `json:"ff"`
   URL    string `json:"url"`
   Type   string `json:"type"`
   Inside []struct {
    Aa struct {
     Zz float64 `json:"zz"`
    } `json:"aa"`
    Bb int `json:"bb"`
   } `json:"inside"`
  } `json:"avatars"`
 } `json:"person"`
 Company struct {
  Name string    `json:"name"`
  List []float64 `json:"list"`
  Strs []string  `json:"strs"`
 } `json:"company"`
}

func func1(ByteData []byte) (result []string, err error) {
		var temp Template1
		// err = json.NewDecoder(bytes.NewReader(ByteData)).Decode(&temp)
		err = json.Unmarshal(ByteData, &temp)
		if err != nil {
			return nil, err
		}
		result = append(result, fmt.Sprint(temp.Person.Name.First))
		return result, nil
	}
 type Template2 struct {
 Person struct {
  Name struct {
   First    string `json:"first"`
   Last     string `json:"last"`
   FullName string `json:"fullName"`
  } `json:"name"`
  Github struct {
   Handle    string `json:"handle"`
   Followers int    `json:"followers"`
  } `json:"github"`
  Avatars []struct {
   Ff     int64  `json:"ff"`
   URL    string `json:"url"`
   Type   string `json:"type"`
   Inside []struct {
    Aa struct {
     Zz float64 `json:"zz"`
    } `json:"aa"`
    Bb int `json:"bb"`
   } `json:"inside"`
  } `json:"avatars"`
 } `json:"person"`
 Company struct {
  Name string    `json:"name"`
  List []float64 `json:"list"`
  Strs []string  `json:"strs"`
 } `json:"company"`
}

func func2(ByteData []byte) (result []string, err error) {
		var temp Template2
		// err = json.NewDecoder(bytes.NewReader(ByteData)).Decode(&temp)
		err = json.Unmarshal(ByteData, &temp)
		if err != nil {
			return nil, err
		}
		for _,v:= range temp.Company.List{
			result = append(result, fmt.Sprint(v))
		}
		return result, nil
	}
 type Template3 struct {
 Person struct {
  Name struct {
   First    string `json:"first"`
   Last     string `json:"last"`
   FullName string `json:"fullName"`
  } `json:"name"`
  Github struct {
   Handle    string `json:"handle"`
   Followers int    `json:"followers"`
  } `json:"github"`
  Avatars []struct {
   Ff     int64  `json:"ff"`
   URL    string `json:"url"`
   Type   string `json:"type"`
   Inside []struct {
    Aa struct {
     Zz float64 `json:"zz"`
    } `json:"aa"`
    Bb int `json:"bb"`
   } `json:"inside"`
  } `json:"avatars"`
 } `json:"person"`
 Company struct {
  Name string    `json:"name"`
  List []float64 `json:"list"`
  Strs []string  `json:"strs"`
 } `json:"company"`
}

func func3(ByteData []byte) (result []string, err error) {
		var temp Template3
		// err = json.NewDecoder(bytes.NewReader(ByteData)).Decode(&temp)
		err = json.Unmarshal(ByteData, &temp)
		if err != nil {
			return nil, err
		}
		result = append(result, fmt.Sprint(temp.Person.Github.Followers))
		return result, nil
	}
 type Template5 struct {
 Person struct {
  Name struct {
   First    string `json:"first"`
   Last     string `json:"last"`
   FullName string `json:"fullName"`
  } `json:"name"`
  Github struct {
   Handle    string `json:"handle"`
   Followers int64    `json:"followers"`
  } `json:"github"`
  Avatars []struct {
   Ff     int64  `json:"ff"`
   URL    string `json:"url"`
   Type   string `json:"type"`
   Inside []struct {
    Aa struct {
     Zz float64 `json:"zz"`
    } `json:"aa"`
    Bb int `json:"bb"`
   } `json:"inside"`
  } `json:"avatars"`
 } `json:"person"`
 Company struct {
  Name string    `json:"name"`
  List []float64 `json:"list"`
  Strs []string  `json:"strs"`
 } `json:"company"`
}


func func5(ByteData []byte) (result []string, err error) {
		var temp Template5
		// err = json.NewDecoder(bytes.NewReader(ByteData)).Decode(&temp)
		err = json.Unmarshal(ByteData, &temp)
		if err != nil {
			return nil, err
		}
		result = append(result, fmt.Sprint(temp.Person.Github.Followers))
		return result, nil
	}
 type Template6 struct {
 Person struct {
  Name struct {
   First    string `json:"first"`
   Last     string `json:"last"`
   FullName string `json:"fullName"`
  } `json:"name"`
  Github struct {
   Handle    string `json:"handle"`
   Followers int64    `json:"followers"`
  } `json:"github"`
  Avatars []struct {
   Ff     int64  `json:"ff"`
   URL    string `json:"url"`
   Type   string `json:"type"`
   Inside []struct {
    Aa struct {
     Zz float64 `json:"zz"`
    } `json:"aa"`
    Bb int `json:"bb"`
   } `json:"inside"`
  } `json:"avatars"`
 } `json:"person"`
 Company struct {
  Name string    `json:"name"`
  List []float64 `json:"list"`
  Strs []string  `json:"strs"`
 } `json:"company"`
}


func func6(ByteData []byte) (result []string, err error) {
		var temp Template6
		// err = json.NewDecoder(bytes.NewReader(ByteData)).Decode(&temp)
		err = json.Unmarshal(ByteData, &temp)
		if err != nil {
			return nil, err
		}
		result = append(result, fmt.Sprint(temp.Person.Name.First))
		return result, nil
	}
 type Template7 struct {
 Person struct {
  Name struct {
   First    string `json:"first"`
   Last     string `json:"last"`
   FullName string `json:"fullName"`
  } `json:"name"`
  Github struct {
   Handle    string `json:"handle"`
   Followers int64    `json:"followers"`
  } `json:"github"`
  Avatars []struct {
   Ff     int64  `json:"ff"`
   URL    string `json:"url"`
   Type   string `json:"type"`
   Inside []struct {
    Aa struct {
     Zz float64 `json:"zz"`
    } `json:"aa"`
    Bb int `json:"bb"`
   } `json:"inside"`
  } `json:"avatars"`
 } `json:"person"`
 Company struct {
  Name string    `json:"name"`
  List []float64 `json:"list"`
  Strs []string  `json:"strs"`
 } `json:"company"`
}


func func7(ByteData []byte) (result []string, err error) {
		var temp Template7
		// err = json.NewDecoder(bytes.NewReader(ByteData)).Decode(&temp)
		err = json.Unmarshal(ByteData, &temp)
		if err != nil {
			return nil, err
		}
		for _,v:= range temp.Company.List{
			result = append(result, fmt.Sprint(v))
		}
		return result, nil
	}
 type Template8 struct {
 Person struct {
  Name struct {
   First    string `json:"first"`
   Last     string `json:"last"`
   FullName string `json:"fullName"`
  } `json:"name"`
  Github struct {
   Handle    string `json:"handle"`
   Followers int64    `json:"followers"`
  } `json:"github"`
  Avatars []struct {
   Ff     int64  `json:"ff"`
   URL    string `json:"url"`
   Type   string `json:"type"`
   Inside []struct {
    Aa struct {
     Zz float64 `json:"zz"`
    } `json:"aa"`
    Bb int `json:"bb"`
   } `json:"inside"`
  } `json:"avatars"`
 } `json:"person"`
 Company struct {
  Name string    `json:"name"`
  List []float64 `json:"list"`
  Strs []string  `json:"strs"`
 } `json:"company"`
}


func func8(ByteData []byte) (result []string, err error) {
		var temp Template8
		// err = json.NewDecoder(bytes.NewReader(ByteData)).Decode(&temp)
		err = json.Unmarshal(ByteData, &temp)
		if err != nil {
			return nil, err
		}
		for _,v:= range temp.Company.Strs{
			result = append(result, fmt.Sprint(v))
		}
		return result, nil
	}
 type Template9 struct {
 Person struct {
  Name struct {
   First    string `json:"first"`
   Last     string `json:"last"`
   FullName string `json:"fullName"`
  } `json:"name"`
  Github struct {
   Handle    string `json:"handle"`
   Followers int64    `json:"followers"`
  } `json:"github"`
  Avatars []struct {
   Ff     int64  `json:"ff"`
   URL    string `json:"url"`
   Type   string `json:"type"`
   Inside []struct {
    Aa struct {
     Zz float64 `json:"zz"`
    } `json:"aa"`
    Bb int `json:"bb"`
   } `json:"inside"`
  } `json:"avatars"`
 } `json:"person"`
 Company struct {
  Name string    `json:"name"`
  List []float64 `json:"list"`
  Strs []string  `json:"strs"`
 } `json:"company"`
}


func func9(ByteData []byte) (result []string, err error) {
		var temp Template9
		// err = json.NewDecoder(bytes.NewReader(ByteData)).Decode(&temp)
		err = json.Unmarshal(ByteData, &temp)
		if err != nil {
			return nil, err
		}
		for _,v:= range temp.Person.Avatars{
			result = append(result, fmt.Sprint(v.Ff))
		}
		return result, nil
	}
